### ISSUE TITLE
Code generated for Flutter is in wrong format

### ISSUE THREAD

**Issue by ineffablesam** [Eronred/shadow-generator-react-native-flutter#2]
**Issue Description:**

The provided code snippet has syntax errors and needs correction. 

**Code Snippet:**

```dart
BoxShadow(
  color: Colors.[#000000].withOpacity(1),
  offset: const Offset(8, 8,),
  blurRadius: 0,
  spreadRadius: 4,
)
```

The correct code for the flutter is 

```dart
BoxShadow(
  color: Color(0xFF000000).withOpacity(1),
  offset: Offset(8, 8),
  blurRadius: 0,
  spreadRadius: 4,
)
```

**Explanation**

Colors.[#000000] should be Color(0xFF000000). The Color class in Flutter requires a hexadecimal value to represent colors. The _0xFF_ prefix indicates the alpha value (opacity) of the color, and the following six digits represent the RGB values. In this case, #000000 represents black.

**Comment by Eronred** [comment]
Thank you for reporting the issue. I realized it wasn't the correct way to implement the Flutter feature. Although I provided a hex color, any pull request is welcome.

**Comment by ineffablesam** [comment]
Added a PR with the Fix for Flutter,
Do check it once before merging it, Haven't checked if my changes had broken any generation for React Native
